import Head from "next/head";
import NavBar from "@/components/NavBar";
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from "@/components/Fouter";

// import Footer from "@/components/fouter";

export const metadata = {
  title: "Ecole",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang='en'>
    <body className=" bg-white {inter.className}">
      <NavBar/>
      {children}
      <Footer/>
      </body>
   </html>
  );
}